### ISSUE TITLE
Product Detail Page

### ISSUE THREAD

**Issue by good-idea** [good-idea/spinellikilcollin.com#23]
- [ ] _on hold_  ~Update images / gallery / content blocks~
- [ ] Multi - carousel
   - It looks like there will be two "tabs" for the related items carousels. Add these and make them switchable -- you can use the same data for both carousels for now
- [x] Footer - Add a standalone Footer component, just use placeholder content for now

**Comment by misteroh10302** [comment]
@good-idea 

We need to add a text color field in the backend for the Content blocks for each product. Otherwise, we wont be able to control the color of the text over the background images.

I couldn't find where this was - so lmk if I can create the content model myself!

**Comment by misteroh10302** [comment]
Some pages with content you can look at:

/products/luna
/products/luna-bg
/products/mini-micro-hoop-pave-gris

@good-idea
