### ISSUE TITLE
Hero Block

### ISSUE THREAD

**Issue by good-idea** [good-idea/spinellikilcollin.com#27]
There is a `textPosition` and `mobileTextPosition` prop you can use to position the text.

Also, you can use the  `<RichText />` component to render the `bodyRaw` data. (If the actual text sizes don't match those in the designs, don't worry about it for right now)

- [x] Mobile styling
- [x] Let's have the ratio fixed, instead of tied to the viewport. Since they'll have text over these images, it might get funky on different screen sizes. When I have a tall, narrow browser window on my desktop monitor, it looks like this:

![image](https://user-images.githubusercontent.com/11514928/64570018-0fd5fe80-d314-11e9-9b32-81a1dd3415c5.png)

**Comment by good-idea** [comment]
- [ ] Mobile styling
- [ ] Let's have the ratio fixed, instead of tied to the viewport. Since they'll have text over these images, it might get funky on different screen sizes. When I have a tall, narrow browser window on my desktop monitor, it looks like this:

![image](https://user-images.githubusercontent.com/11514928/64570018-0fd5fe80-d314-11e9-9b32-81a1dd3415c5.png)

**Comment by misteroh10302** [comment]
#34
